### ISSUE TITLE
CSS Touch Ups

### ISSUE THREAD

**Issue by Aphillip22** [Gelenhaus/groupProject1#10]
-radio button and form input css
-js card element css

**Comment by JD-Rowley** [comment]
I added some margin in between the radio buttons and restructured the html for the form for an easier to read result.
I also designed a card layout, but I'm having some trouble making the two columns appear together in one row.
The last issue I fixed was the problem where the nav bar went behind the form while scrolling.
I will push the current branch up to develop when I have fixed the issue with the card elements.
